#!/usr/bin/env python3
"""Minimal deterministic stand-in for a live LLM executor.

Reads the composed agent prompt on stdin and prints a markdown artifact that proves the
prompt actually flowed through this process (length + content hash + echoed head). It is
NOT an LLM — it is a reproducible placeholder for wiring/QA.

Swap it for a real model by pointing --executor-cmd at one, e.g.:

    uv run aicmo run blog-article --client sample-client-a --topic "기업 꽃 구독" \
        --executor-cmd "claude -p"
    ... --executor-cmd "codex exec"
    ... --executor-cmd "ollama run llama3"
"""

from __future__ import annotations

import hashlib
import sys


def main() -> int:
    prompt = sys.stdin.read()
    digest = hashlib.sha256(prompt.encode("utf-8")).hexdigest()[:12]
    head = "\n".join(f"> {line}" for line in prompt.splitlines()[:8])
    sys.stdout.write(
        "# Generated by echo-executor (deterministic stand-in)\n\n"
        f"- prompt_chars: {len(prompt)}\n"
        f"- prompt_sha256_12: {digest}\n\n"
        "## Echoed prompt head\n\n"
        f"{head}\n",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
