# Generated by Django 5.2.17 on 2026-09-06 05:16

import uuid
from typing import ClassVar

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: ClassVar = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations: ClassVar = [
        migrations.CreateModel(
            name="LoginWindow",
            fields=[
                ("key", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("failures", models.PositiveIntegerField(default=0)),
                ("opened_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("client", models.SlugField(max_length=128, unique=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "permissions": (("operate_stores", "Access and operate all stores"),),
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("submission_key", models.UUIDField()),
                ("inputs", models.JSONField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("queued", "접수됨"),
                            ("running", "작성 중"),
                            ("waiting_approval", "사장님 확인"),
                            ("success", "저장 가능"),
                            ("needs_work", "검토 필요"),
                            ("failed", "작업 실패"),
                            ("cancelled", "취소됨"),
                        ],
                        default="queued",
                        max_length=24,
                    ),
                ),
                ("approval", models.JSONField(default=dict)),
                ("cancel_requested", models.BooleanField(default=False)),
                ("notice", models.CharField(blank=True, max_length=240)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="store_app.store"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("store", "submission_key"), name="store_submission"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("state__in", ["queued", "running", "waiting_approval"])
                        ),
                        fields=("store",),
                        name="store_one_active_job",
                    ),
                ],
            },
        ),
    ]
