# Generated by Django 5.2.17 on 2026-09-06 06:21

import uuid
from typing import ClassVar

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar = [
        ("store_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations: ClassVar = [
        migrations.CreateModel(
            name="OnboardingDraft",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("data", models.JSONField(default=dict)),
                ("revision", models.PositiveBigIntegerField(default=0)),
                ("completed_step", models.PositiveSmallIntegerField(default=0)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "작성 중"),
                            ("queued", "접수됨"),
                            ("running", "가게 준비 중"),
                            ("failed", "확인 필요"),
                            ("complete", "가게 준비 완료"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("output_hashes", models.JSONField(default=dict)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("failure_code", models.CharField(blank=True, default="", max_length=32)),
                ("stage_id", models.UUIDField(blank=True, editable=False, null=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "store",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="store_app.store",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("completed_step__lte", 3)), name="onboarding_steps"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("state", "complete"), ("store__isnull", False)),
                            models.Q(
                                models.Q(("state", "complete"), _negated=True),
                                ("store__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="onboarding_completed_store",
                    ),
                ],
            },
        ),
    ]
