# Generated by Django 5.2.17 on 2026-09-08 01:36

from typing import ClassVar

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar = [
        ("store_app", "0003_edit_drafts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations: ClassVar = [
        migrations.CreateModel(
            name="PublicationReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("bundle_sha256", models.CharField(max_length=64)),
                ("item_key", models.CharField(max_length=16)),
                ("file_sha256", models.CharField(max_length=64)),
                ("revision", models.PositiveBigIntegerField()),
                ("posted_on", models.DateField(blank=True, null=True)),
                ("request_key", models.UUIDField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="store_app.job"
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("job", "bundle_sha256", "item_key", "revision"),
                        name="publication_item_revision",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("revision__gte", 1)), name="publication_revision"
                    ),
                ],
            },
        ),
    ]
